# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import threads_pb2 as threads__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='projects.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eprojects.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rthreads.proto\"\x9c\x01\n\x07Project\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\x14\n\x0cproject_name\x18\x02 \x01(\t\x12\x0f\n\x07tagline\x18\x03 \x01(\t\x12\x18\n\x07threads\x18\x04 \x03(\x0b\x32\x07.Thread\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"#\n\x12GetProjectsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"1\n\x13GetProjectsResponse\x12\x1a\n\x08projects\x18\x01 \x03(\x0b\x32\x08.Project\".\n\x18GetProjectDetailsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\"6\n\x19GetProjectDetailsResponse\x12\x19\n\x07project\x18\x01 \x01(\x0b\x32\x08.Project\"8\n\x1bUpdateProjectDetailsRequest\x12\x19\n\x07project\x18\x01 \x01(\x0b\x32\x08.Project\"\x1e\n\x1cUpdateProjectDetailsResponse2\xec\x01\n\x0fProjectsService\x12\x38\n\x0bGetProjects\x12\x13.GetProjectsRequest\x1a\x14.GetProjectsResponse\x12J\n\x11GetProjectDetails\x12\x19.GetProjectDetailsRequest\x1a\x1a.GetProjectDetailsResponse\x12S\n\x14UpdateProjectDetails\x12\x1c.UpdateProjectDetailsRequest\x1a\x1d.UpdateProjectDetailsResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,threads__pb2.DESCRIPTOR,])




_PROJECT = _descriptor.Descriptor(
  name='Project',
  full_name='Project',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='Project.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_name', full_name='Project.project_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tagline', full_name='Project.tagline', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threads', full_name='Project.threads', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Project.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='Project.created_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=223,
)


_GETPROJECTSREQUEST = _descriptor.Descriptor(
  name='GetProjectsRequest',
  full_name='GetProjectsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetProjectsRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=260,
)


_GETPROJECTSRESPONSE = _descriptor.Descriptor(
  name='GetProjectsResponse',
  full_name='GetProjectsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='projects', full_name='GetProjectsResponse.projects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=311,
)


_GETPROJECTDETAILSREQUEST = _descriptor.Descriptor(
  name='GetProjectDetailsRequest',
  full_name='GetProjectDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='GetProjectDetailsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=359,
)


_GETPROJECTDETAILSRESPONSE = _descriptor.Descriptor(
  name='GetProjectDetailsResponse',
  full_name='GetProjectDetailsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='GetProjectDetailsResponse.project', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=415,
)


_UPDATEPROJECTDETAILSREQUEST = _descriptor.Descriptor(
  name='UpdateProjectDetailsRequest',
  full_name='UpdateProjectDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='UpdateProjectDetailsRequest.project', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=473,
)


_UPDATEPROJECTDETAILSRESPONSE = _descriptor.Descriptor(
  name='UpdateProjectDetailsResponse',
  full_name='UpdateProjectDetailsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=505,
)

_PROJECT.fields_by_name['threads'].message_type = threads__pb2._THREAD
_PROJECT.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETPROJECTSRESPONSE.fields_by_name['projects'].message_type = _PROJECT
_GETPROJECTDETAILSRESPONSE.fields_by_name['project'].message_type = _PROJECT
_UPDATEPROJECTDETAILSREQUEST.fields_by_name['project'].message_type = _PROJECT
DESCRIPTOR.message_types_by_name['Project'] = _PROJECT
DESCRIPTOR.message_types_by_name['GetProjectsRequest'] = _GETPROJECTSREQUEST
DESCRIPTOR.message_types_by_name['GetProjectsResponse'] = _GETPROJECTSRESPONSE
DESCRIPTOR.message_types_by_name['GetProjectDetailsRequest'] = _GETPROJECTDETAILSREQUEST
DESCRIPTOR.message_types_by_name['GetProjectDetailsResponse'] = _GETPROJECTDETAILSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateProjectDetailsRequest'] = _UPDATEPROJECTDETAILSREQUEST
DESCRIPTOR.message_types_by_name['UpdateProjectDetailsResponse'] = _UPDATEPROJECTDETAILSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Project = _reflection.GeneratedProtocolMessageType('Project', (_message.Message,), {
  'DESCRIPTOR' : _PROJECT,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:Project)
  })
_sym_db.RegisterMessage(Project)

GetProjectsRequest = _reflection.GeneratedProtocolMessageType('GetProjectsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTSREQUEST,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectsRequest)
  })
_sym_db.RegisterMessage(GetProjectsRequest)

GetProjectsResponse = _reflection.GeneratedProtocolMessageType('GetProjectsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTSRESPONSE,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectsResponse)
  })
_sym_db.RegisterMessage(GetProjectsResponse)

GetProjectDetailsRequest = _reflection.GeneratedProtocolMessageType('GetProjectDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTDETAILSREQUEST,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectDetailsRequest)
  })
_sym_db.RegisterMessage(GetProjectDetailsRequest)

GetProjectDetailsResponse = _reflection.GeneratedProtocolMessageType('GetProjectDetailsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTDETAILSRESPONSE,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectDetailsResponse)
  })
_sym_db.RegisterMessage(GetProjectDetailsResponse)

UpdateProjectDetailsRequest = _reflection.GeneratedProtocolMessageType('UpdateProjectDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPROJECTDETAILSREQUEST,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:UpdateProjectDetailsRequest)
  })
_sym_db.RegisterMessage(UpdateProjectDetailsRequest)

UpdateProjectDetailsResponse = _reflection.GeneratedProtocolMessageType('UpdateProjectDetailsResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPROJECTDETAILSRESPONSE,
  '__module__' : 'projects_pb2'
  # @@protoc_insertion_point(class_scope:UpdateProjectDetailsResponse)
  })
_sym_db.RegisterMessage(UpdateProjectDetailsResponse)



_PROJECTSSERVICE = _descriptor.ServiceDescriptor(
  name='ProjectsService',
  full_name='ProjectsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=508,
  serialized_end=744,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProjects',
    full_name='ProjectsService.GetProjects',
    index=0,
    containing_service=None,
    input_type=_GETPROJECTSREQUEST,
    output_type=_GETPROJECTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetProjectDetails',
    full_name='ProjectsService.GetProjectDetails',
    index=1,
    containing_service=None,
    input_type=_GETPROJECTDETAILSREQUEST,
    output_type=_GETPROJECTDETAILSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateProjectDetails',
    full_name='ProjectsService.UpdateProjectDetails',
    index=2,
    containing_service=None,
    input_type=_UPDATEPROJECTDETAILSREQUEST,
    output_type=_UPDATEPROJECTDETAILSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROJECTSSERVICE)

DESCRIPTOR.services_by_name['ProjectsService'] = _PROJECTSSERVICE

# @@protoc_insertion_point(module_scope)
