# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threads.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='threads.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rthreads.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x06Thread\x12\x11\n\tthread_id\x18\x01 \x01(\x04\x12\x12\n\nproject_id\x18\x02 \x01(\x04\x12\x13\n\x0bthread_type\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"=\n\x18GetProjectThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\r\n\x05limit\x18\x02 \x01(\x05\"5\n\x19GetProjectThreadsResponse\x12\x18\n\x07threads\x18\x01 \x03(\x0b\x32\x07.Thread\"L\n\x14GetSubThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\x11\n\tthread_id\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x05\"1\n\x15GetSubThreadsResponse\x12\x18\n\x07threads\x18\x01 \x03(\x0b\x32\x07.Thread\"D\n\x14UpdateThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\x18\n\x07threads\x18\x02 \x03(\x0b\x32\x07.Thread\"\x17\n\x15UpdateThreadsResponse*4\n\nThreadType\x12\x0b\n\x07\x43OMMENT\x10\x00\x12\x0c\n\x08SOLUTION\x10\x01\x12\x0b\n\x07PROBLEM\x10\x02\x32\xd8\x01\n\nThreadsSvc\x12J\n\x11GetProjectThreads\x12\x19.GetProjectThreadsRequest\x1a\x1a.GetProjectThreadsResponse\x12>\n\rGetSubThreads\x12\x15.GetSubThreadsRequest\x1a\x16.GetSubThreadsResponse\x12>\n\rUpdateThreads\x12\x15.UpdateThreadsRequest\x1a\x16.UpdateThreadsResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_THREADTYPE = _descriptor.EnumDescriptor(
  name='ThreadType',
  full_name='ThreadType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLUTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROBLEM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=528,
  serialized_end=580,
)
_sym_db.RegisterEnumDescriptor(_THREADTYPE)

ThreadType = enum_type_wrapper.EnumTypeWrapper(_THREADTYPE)
COMMENT = 0
SOLUTION = 1
PROBLEM = 2



_THREAD = _descriptor.Descriptor(
  name='Thread',
  full_name='Thread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='Thread.thread_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='Thread.project_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_type', full_name='Thread.thread_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Thread.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='Thread.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=184,
)


_GETPROJECTTHREADSREQUEST = _descriptor.Descriptor(
  name='GetProjectThreadsRequest',
  full_name='GetProjectThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='GetProjectThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetProjectThreadsRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=247,
)


_GETPROJECTTHREADSRESPONSE = _descriptor.Descriptor(
  name='GetProjectThreadsResponse',
  full_name='GetProjectThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='threads', full_name='GetProjectThreadsResponse.threads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=302,
)


_GETSUBTHREADSREQUEST = _descriptor.Descriptor(
  name='GetSubThreadsRequest',
  full_name='GetSubThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='GetSubThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='GetSubThreadsRequest.thread_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetSubThreadsRequest.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=380,
)


_GETSUBTHREADSRESPONSE = _descriptor.Descriptor(
  name='GetSubThreadsResponse',
  full_name='GetSubThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='threads', full_name='GetSubThreadsResponse.threads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=431,
)


_UPDATETHREADSREQUEST = _descriptor.Descriptor(
  name='UpdateThreadsRequest',
  full_name='UpdateThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='UpdateThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threads', full_name='UpdateThreadsRequest.threads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=501,
)


_UPDATETHREADSRESPONSE = _descriptor.Descriptor(
  name='UpdateThreadsResponse',
  full_name='UpdateThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=526,
)

_THREAD.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETPROJECTTHREADSRESPONSE.fields_by_name['threads'].message_type = _THREAD
_GETSUBTHREADSRESPONSE.fields_by_name['threads'].message_type = _THREAD
_UPDATETHREADSREQUEST.fields_by_name['threads'].message_type = _THREAD
DESCRIPTOR.message_types_by_name['Thread'] = _THREAD
DESCRIPTOR.message_types_by_name['GetProjectThreadsRequest'] = _GETPROJECTTHREADSREQUEST
DESCRIPTOR.message_types_by_name['GetProjectThreadsResponse'] = _GETPROJECTTHREADSRESPONSE
DESCRIPTOR.message_types_by_name['GetSubThreadsRequest'] = _GETSUBTHREADSREQUEST
DESCRIPTOR.message_types_by_name['GetSubThreadsResponse'] = _GETSUBTHREADSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateThreadsRequest'] = _UPDATETHREADSREQUEST
DESCRIPTOR.message_types_by_name['UpdateThreadsResponse'] = _UPDATETHREADSRESPONSE
DESCRIPTOR.enum_types_by_name['ThreadType'] = _THREADTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Thread = _reflection.GeneratedProtocolMessageType('Thread', (_message.Message,), {
  'DESCRIPTOR' : _THREAD,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:Thread)
  })
_sym_db.RegisterMessage(Thread)

GetProjectThreadsRequest = _reflection.GeneratedProtocolMessageType('GetProjectThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTTHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectThreadsRequest)
  })
_sym_db.RegisterMessage(GetProjectThreadsRequest)

GetProjectThreadsResponse = _reflection.GeneratedProtocolMessageType('GetProjectThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTTHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:GetProjectThreadsResponse)
  })
_sym_db.RegisterMessage(GetProjectThreadsResponse)

GetSubThreadsRequest = _reflection.GeneratedProtocolMessageType('GetSubThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBTHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:GetSubThreadsRequest)
  })
_sym_db.RegisterMessage(GetSubThreadsRequest)

GetSubThreadsResponse = _reflection.GeneratedProtocolMessageType('GetSubThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBTHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:GetSubThreadsResponse)
  })
_sym_db.RegisterMessage(GetSubThreadsResponse)

UpdateThreadsRequest = _reflection.GeneratedProtocolMessageType('UpdateThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:UpdateThreadsRequest)
  })
_sym_db.RegisterMessage(UpdateThreadsRequest)

UpdateThreadsResponse = _reflection.GeneratedProtocolMessageType('UpdateThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:UpdateThreadsResponse)
  })
_sym_db.RegisterMessage(UpdateThreadsResponse)



_THREADSSVC = _descriptor.ServiceDescriptor(
  name='ThreadsSvc',
  full_name='ThreadsSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=583,
  serialized_end=799,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProjectThreads',
    full_name='ThreadsSvc.GetProjectThreads',
    index=0,
    containing_service=None,
    input_type=_GETPROJECTTHREADSREQUEST,
    output_type=_GETPROJECTTHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubThreads',
    full_name='ThreadsSvc.GetSubThreads',
    index=1,
    containing_service=None,
    input_type=_GETSUBTHREADSREQUEST,
    output_type=_GETSUBTHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateThreads',
    full_name='ThreadsSvc.UpdateThreads',
    index=2,
    containing_service=None,
    input_type=_UPDATETHREADSREQUEST,
    output_type=_UPDATETHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_THREADSSVC)

DESCRIPTOR.services_by_name['ThreadsSvc'] = _THREADSSVC

# @@protoc_insertion_point(module_scope)
