# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threads.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='threads.proto',
  package='pylib.proto.threads',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rthreads.proto\x12\x13pylib.proto.threads\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x06Thread\x12\x11\n\tthread_id\x18\x01 \x01(\x04\x12\x12\n\nproject_id\x18\x02 \x01(\x04\x12\x13\n\x0bthread_type\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"=\n\x18GetProjectThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\r\n\x05limit\x18\x02 \x01(\x05\"I\n\x19GetProjectThreadsResponse\x12,\n\x07threads\x18\x01 \x03(\x0b\x32\x1b.pylib.proto.threads.Thread\"L\n\x14GetSubThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12\x11\n\tthread_id\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x05\"E\n\x15GetSubThreadsResponse\x12,\n\x07threads\x18\x01 \x03(\x0b\x32\x1b.pylib.proto.threads.Thread\"X\n\x14UpdateThreadsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x04\x12,\n\x07threads\x18\x02 \x03(\x0b\x32\x1b.pylib.proto.threads.Thread\"\x17\n\x15UpdateThreadsResponse*4\n\nThreadType\x12\x0b\n\x07\x43OMMENT\x10\x00\x12\x0c\n\x08SOLUTION\x10\x01\x12\x0b\n\x07PROBLEM\x10\x02\x32\xd4\x02\n\x0eThreadsService\x12r\n\x11GetProjectThreads\x12-.pylib.proto.threads.GetProjectThreadsRequest\x1a..pylib.proto.threads.GetProjectThreadsResponse\x12\x66\n\rGetSubThreads\x12).pylib.proto.threads.GetSubThreadsRequest\x1a*.pylib.proto.threads.GetSubThreadsResponse\x12\x66\n\rUpdateThreads\x12).pylib.proto.threads.UpdateThreadsRequest\x1a*.pylib.proto.threads.UpdateThreadsResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_THREADTYPE = _descriptor.EnumDescriptor(
  name='ThreadType',
  full_name='pylib.proto.threads.ThreadType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOLUTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROBLEM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=609,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_THREADTYPE)

ThreadType = enum_type_wrapper.EnumTypeWrapper(_THREADTYPE)
COMMENT = 0
SOLUTION = 1
PROBLEM = 2



_THREAD = _descriptor.Descriptor(
  name='Thread',
  full_name='pylib.proto.threads.Thread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='pylib.proto.threads.Thread.thread_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='pylib.proto.threads.Thread.project_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_type', full_name='pylib.proto.threads.Thread.thread_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='pylib.proto.threads.Thread.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='pylib.proto.threads.Thread.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=205,
)


_GETPROJECTTHREADSREQUEST = _descriptor.Descriptor(
  name='GetProjectThreadsRequest',
  full_name='pylib.proto.threads.GetProjectThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='pylib.proto.threads.GetProjectThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='pylib.proto.threads.GetProjectThreadsRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=268,
)


_GETPROJECTTHREADSRESPONSE = _descriptor.Descriptor(
  name='GetProjectThreadsResponse',
  full_name='pylib.proto.threads.GetProjectThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='threads', full_name='pylib.proto.threads.GetProjectThreadsResponse.threads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=343,
)


_GETSUBTHREADSREQUEST = _descriptor.Descriptor(
  name='GetSubThreadsRequest',
  full_name='pylib.proto.threads.GetSubThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='pylib.proto.threads.GetSubThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='pylib.proto.threads.GetSubThreadsRequest.thread_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='pylib.proto.threads.GetSubThreadsRequest.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=421,
)


_GETSUBTHREADSRESPONSE = _descriptor.Descriptor(
  name='GetSubThreadsResponse',
  full_name='pylib.proto.threads.GetSubThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='threads', full_name='pylib.proto.threads.GetSubThreadsResponse.threads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=492,
)


_UPDATETHREADSREQUEST = _descriptor.Descriptor(
  name='UpdateThreadsRequest',
  full_name='pylib.proto.threads.UpdateThreadsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_id', full_name='pylib.proto.threads.UpdateThreadsRequest.project_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threads', full_name='pylib.proto.threads.UpdateThreadsRequest.threads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=582,
)


_UPDATETHREADSRESPONSE = _descriptor.Descriptor(
  name='UpdateThreadsResponse',
  full_name='pylib.proto.threads.UpdateThreadsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=607,
)

_THREAD.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETPROJECTTHREADSRESPONSE.fields_by_name['threads'].message_type = _THREAD
_GETSUBTHREADSRESPONSE.fields_by_name['threads'].message_type = _THREAD
_UPDATETHREADSREQUEST.fields_by_name['threads'].message_type = _THREAD
DESCRIPTOR.message_types_by_name['Thread'] = _THREAD
DESCRIPTOR.message_types_by_name['GetProjectThreadsRequest'] = _GETPROJECTTHREADSREQUEST
DESCRIPTOR.message_types_by_name['GetProjectThreadsResponse'] = _GETPROJECTTHREADSRESPONSE
DESCRIPTOR.message_types_by_name['GetSubThreadsRequest'] = _GETSUBTHREADSREQUEST
DESCRIPTOR.message_types_by_name['GetSubThreadsResponse'] = _GETSUBTHREADSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateThreadsRequest'] = _UPDATETHREADSREQUEST
DESCRIPTOR.message_types_by_name['UpdateThreadsResponse'] = _UPDATETHREADSRESPONSE
DESCRIPTOR.enum_types_by_name['ThreadType'] = _THREADTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Thread = _reflection.GeneratedProtocolMessageType('Thread', (_message.Message,), {
  'DESCRIPTOR' : _THREAD,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.Thread)
  })
_sym_db.RegisterMessage(Thread)

GetProjectThreadsRequest = _reflection.GeneratedProtocolMessageType('GetProjectThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTTHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.GetProjectThreadsRequest)
  })
_sym_db.RegisterMessage(GetProjectThreadsRequest)

GetProjectThreadsResponse = _reflection.GeneratedProtocolMessageType('GetProjectThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPROJECTTHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.GetProjectThreadsResponse)
  })
_sym_db.RegisterMessage(GetProjectThreadsResponse)

GetSubThreadsRequest = _reflection.GeneratedProtocolMessageType('GetSubThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBTHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.GetSubThreadsRequest)
  })
_sym_db.RegisterMessage(GetSubThreadsRequest)

GetSubThreadsResponse = _reflection.GeneratedProtocolMessageType('GetSubThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSUBTHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.GetSubThreadsResponse)
  })
_sym_db.RegisterMessage(GetSubThreadsResponse)

UpdateThreadsRequest = _reflection.GeneratedProtocolMessageType('UpdateThreadsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETHREADSREQUEST,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.UpdateThreadsRequest)
  })
_sym_db.RegisterMessage(UpdateThreadsRequest)

UpdateThreadsResponse = _reflection.GeneratedProtocolMessageType('UpdateThreadsResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETHREADSRESPONSE,
  '__module__' : 'threads_pb2'
  # @@protoc_insertion_point(class_scope:pylib.proto.threads.UpdateThreadsResponse)
  })
_sym_db.RegisterMessage(UpdateThreadsResponse)



_THREADSSERVICE = _descriptor.ServiceDescriptor(
  name='ThreadsService',
  full_name='pylib.proto.threads.ThreadsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=664,
  serialized_end=1004,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProjectThreads',
    full_name='pylib.proto.threads.ThreadsService.GetProjectThreads',
    index=0,
    containing_service=None,
    input_type=_GETPROJECTTHREADSREQUEST,
    output_type=_GETPROJECTTHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubThreads',
    full_name='pylib.proto.threads.ThreadsService.GetSubThreads',
    index=1,
    containing_service=None,
    input_type=_GETSUBTHREADSREQUEST,
    output_type=_GETSUBTHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateThreads',
    full_name='pylib.proto.threads.ThreadsService.UpdateThreads',
    index=2,
    containing_service=None,
    input_type=_UPDATETHREADSREQUEST,
    output_type=_UPDATETHREADSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_THREADSSERVICE)

DESCRIPTOR.services_by_name['ThreadsService'] = _THREADSSERVICE

# @@protoc_insertion_point(module_scope)
